export const T = {
  CHANGE_LOADING: 'CHANGE_LOADING',
  USER_LOGGEDIN: 'USER_LOGGEDIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
  GET_USER_INFO: 'GET_USER_INFO',
  SET_ROUTES: 'SET_ROUTES',
  AJAX_GET_TOP_WEB_WORKS: 'AJAX_GET_TOP_WEB_WORKS',
  AJAX_GET_WORK_THUMBNAIL: 'AJAX_GET_WORK_THUMBNAIL',
  AJAX_GET_THUMBNAIL_ERROR: 'AJAX_GET_THUMBNAIL_ERROR',
  AJAX_POST_WORK_DATA: 'AJAX_POST_WORK_DATA',
  AJAX_POST_WORK_ERROR: 'AJAX_POST_WORK_ERROR',
  AJAX_GET_WORKS_DATA: 'AJAX_GET_WORKS_DATA',
  AJAX_GET_WORKS_DETAIL_DATA: 'AJAX_GET_WORKS_DETAIL_DATA',
  AJAX_GET_DETAIL_ITEMS: 'AJAX_GET_DETAIL_ITEMS'
}
